### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by johnroper100** [UncleSamSwiss/ioBroker.udmx#1]
Hi, can you post an example code if how to use this, please?

**Comment by UncleSamSwiss** [comment]
This is an adapter for ioBroker. You won't be able to use this module directly from a node application. If you're using ioBroker, just install it using the module name ("iobroker.udmx") in manual install.
If you want to use an uDMX adapter from node, have a look at my code; it's really straightforward since the relevant USB protocol is amazingly simple.
If you have further questions, please don't hesitate to ask them here in this thread.
